import type { Candidate, Company, Job } from "@/lib/types";

export const mockCompanies: Company[] = [
  {
    id: "comp_1",
    name: "NovaTech",
    commercial_name: "NovaTech Labs",
    logo_url: "",
    description: "SaaS company focused on HR automation.",
    sector: "Software",
    size: 120,
    type: "startup",
    created_at: new Date().toISOString(),
    website: "https://novatech.example.com",
    country: "Morocco",
    city: "Casablanca",
    address: "Sidi Maarouf",
    postal_code: "20190",
    phone: "+212522000000",
    email: "hr@novatech.example.com",
    timezone: "Africa/Casablanca",
    registration_number: "RC123456",
    tax_id: "TAX123456",
    vat_number: "VAT123456",
    legal_form: "SARL",
    legal_representative: "Salma Idrissi",
    registration_country: "Morocco",
    hr_info: {
      first_name: "Salma",
      last_name: "Idrissi",
      email: "salma@novatech.example.com",
      phone: "+212600111111",
      role: "HR Manager",
    },
    departments: ["Engineering", "Product", "HR"],
    contract_types: ["CDI", "CDD", "Stage"],
    recruitment_language: "FR",
    recruitment_policy: "Equal opportunity hiring.",
  },
  {
    id: "comp_2",
    name: "Atlas Finance",
    commercial_name: "Atlas Finance Group",
    logo_url: "",
    description: "Financial services and data analytics.",
    sector: "Finance",
    size: 400,
    type: "PME",
    created_at: new Date().toISOString(),
    website: "https://atlasfinance.example.com",
    country: "Morocco",
    city: "Rabat",
    address: "Agdal",
    postal_code: "10000",
    phone: "+212537000000",
    email: "careers@atlasfinance.example.com",
    timezone: "Africa/Casablanca",
    registration_number: "RC654321",
    tax_id: "TAX654321",
    vat_number: "VAT654321",
    legal_form: "SA",
    legal_representative: "Youssef El Fassi",
    registration_country: "Morocco",
    hr_info: {
      first_name: "Meryem",
      last_name: "Alaoui",
      email: "meryem@atlasfinance.example.com",
      phone: "+212600222222",
      role: "Talent Acquisition Lead",
    },
    departments: ["Risk", "Data", "Operations"],
    contract_types: ["CDI", "Freelance"],
    recruitment_language: "FR/EN",
    recruitment_policy: "Skills-first recruitment process.",
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: "cand_1",
    first_name: "Amina",
    last_name: "Bensaid",
    birth_date: "1999-02-11",
    nationality: "MA",
    profile_photo: "",
    country: "Morocco",
    city: "Casablanca",
    address: "Maarif",
    postal_code: "20100",
    email: "amina@example.com",
    phone: "+212600000000",
    linkedin: "",
    github: "",
    auth_provider: "email",
    created_at: new Date().toISOString(),
    cv: {
      bio: "Frontend engineer with HR-tech interest.",
      education: [{ start_date: "2018", end_date: "2023", institution: "ENSA", degree: "Master" }],
      experience: [],
      hard_skills: ["react", "next.js", "typescript", "tailwindcss"],
      soft_skills: ["communication", "teamwork"],
      languages: [{ language: "fr", level: "C1" }, { language: "en", level: "B2" }],
      certifications: [{ name: "AWS Practitioner", degree: "associate" }],
    },
  },
  {
    id: "cand_2",
    first_name: "Yassine",
    last_name: "Karimi",
    birth_date: "1997-09-02",
    nationality: "MA",
    profile_photo: "",
    country: "Morocco",
    city: "Rabat",
    address: "Hay Riad",
    postal_code: "10100",
    email: "yassine@example.com",
    phone: "+212611111111",
    linkedin: "",
    github: "",
    auth_provider: "email",
    created_at: new Date().toISOString(),
    cv: {
      bio: "Backend developer specialized in APIs and data pipelines.",
      education: [{ start_date: "2016", end_date: "2021", institution: "EMI", degree: "Engineering" }],
      experience: [],
      hard_skills: ["node.js", "python", "sql", "docker"],
      soft_skills: ["problem solving", "leadership"],
      languages: [{ language: "fr", level: "C1" }, { language: "en", level: "B2" }],
      certifications: [{ name: "Google Cloud Associate", degree: "associate" }],
    },
  },
];

export const mockJobs: Job[] = [
  {
    id: "job_1",
    company_id: "comp_1",
    title: "Frontend Engineer",
    department: "Engineering",
    hard_skills: ["react", "typescript", "next.js", "tailwindcss"],
    soft_skills: ["communication", "autonomy"],
    diplomas: ["Master"],
    certifications: ["AWS Practitioner"],
    languages: ["fr", "en"],
    address: "Casablanca",
    postal_code: "20100",
    positions_count: 2,
    apply_deadline: "2026-06-30",
    interview_deadline: "2026-07-15",
    description: "Build modern SaaS UI for recruitment.",
    created_at: new Date().toISOString(),
  },
];
